---
permalink: reference-types-of-cim-users-and-associated-operations.html 
sidebar: sidebar 
keywords: smi-s provider, various types, control, access 
summary: SMI-S プロバイダを使用する場合は、 CIM サーバーへのアクセスを制御するためにユーザーに割り当てることができるさまざまなタイプのユーザーが存在します。 
---
= CIM ユーザーのタイプと関連する操作
:icons: font
:imagesdir: ./media/


[role="lead"]
SMI-S プロバイダを使用する場合は、 CIM サーバーへのアクセスを制御するためにユーザーに割り当てることができるさまざまなタイプのユーザーが存在します。

このリリース以降、ドメインユーザは SMI-S プロバイダのユーザデータベースおよびその他の設定を、ローカル管理者グループのドメインユーザとして変更できます。

次の表に、 CIM サーバのサポートされているユーザと、各タイプで実行できる操作を示します。

[cols="2*"]
|===
| ユーザのタイプ | 処理 


 a| 
Administrators グループのドメイン管理者
 a| 
SMI-S Provider の構成とユーザー管理には 'cimconfig' コマンドと CIMUser' コマンドを使用します例：

* SMI-S プロバイダの信頼ストアに対してユーザを追加または削除します。
* ログレベルとトレースの設定を有効化、無効化、または変更します。
* SMI-S Provider で認証エンジンを有効または無効にします。


ストレージの管理と検証には 'SMIS` コマンドと 'cimcli` コマンドを使用します例：

* SMI-S プロバイダのリポジトリ、データベース、またはキャッシュに対してストレージコントローラまたは SVM を追加または削除します。
* SMI-S プロバイダキャッシュのストレージコントローラまたは SVM を更新します。
* ストレージコントローラまたは SVM の管理を確認


SCVMM の検出操作。 SCVMM GUI を使用します。



 a| 
ローカル管理者グループのドメインユーザ



 a| 
ローカル管理者グループのローカルユーザ



 a| 
ビルトインドメイン管理者ユーザ



 a| 
ビルトインローカル管理者ユーザ



 a| 
Users グループのドメインユーザ
 a| 
SCVMM の検出操作。 SCVMM GUI を使用します。



 a| 
Users グループのローカルユーザ

|===
[NOTE]
====
Windows ホスト上に SMI-S プロバイダがあり ' いずれかの "Administrator" ユーザー名を変更した場合は ' システムからログアウトしてから再度ログインする必要がありますこの間、 SMI-S Windows サービスは認証を継承します。そのため、管理者がログアウトして再度ログインするまで、クレデンシャルに対する変更は認識されません。

====