---
permalink: reference-hostagentaccessdenied-error-id-26263.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: NetApp SMI-S プロバイダで発生した問題。 
---
= HostAgentAccessDenied （ ID ： 26263 ）
:icons: font
:imagesdir: ./media/




== メッセージ

'Storage provider_SMIS_provider_machine_for user_name failed from _SCVMM __ （ machine ） _ with error code HostAgentAccessDenied （ストレージプロバイダの登録 _SMIS_provider_machine_for user_name で失敗しました。）ストレージ検出に使用する有効なプロバイダ、ポート、およびユーザクレデンシャルを指定してください。ID:2626263`



== 説明

このメッセージは、ユーザーが SCVMM で SMI-S プロバイダに接続するよう指定されていて、 SMIS 信頼ストアの一部ではない場合に表示されます。

SCVMM と SMI-S Provider 間の通信を有効にするには、有効な CIM ユーザー（ローカル管理者ユーザーまたはローカル管理者グループのドメインユーザー）を、「 CIMUser 」コマンドを使用して SMIS 信頼ストアに追加する必要があります。



== 対処方法

「 CIMUser 」コマンドを使用して、ローカル管理者ユーザ（ SMI-S Provider マシン上）を CIM サーバデータベースに追加します。「 CIMUser -a -u admin user 」その後、 NetApp SMI-S プロバイダを SCVMM に追加する際に、その管理ユーザを使用する必要があります。

ドメインコントローラがドメインユーザの認証に時間がかかりすぎる場合は、 SMI-S プロバイダマシンでローカル管理者ユーザを使用する必要があります。

エラーが解消されない場合は、 SMI-S プロバイダで認証を無効にできます。
