---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: SMI-S Provider をインストールする前に、 Windows ホストでサポートされるオペレーティングシステムが実行されていることを確認する必要があります。 
---
= サポートされているオペレーティングシステムのバージョン
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
SMI-S プロバイダーは、専用の Windows 仮想マシン (VM) にインストールすることをお勧めします。この VM は同じドメイン上に配置できるため、安全で便利な管理が可能になります。

SMI-S Provider をインストールする前に、 Windows ホストでサポートされるオペレーティングシステムが実行されていることを確認する必要があります。

[cols="3*"]
|===
| オペレーティングシステム | サポートされるバージョン | 必要なクライアントソフトウェア 


 a| 
Windows の場合
 a| 
* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

 a| 
Microsoft Visual C{pp} 2010 ランタイム ライブラリは、SMI-S プロバイダーのインストール中に自動的にインストールされます。ランタイム ライブラリに関連する潜在的な問題を回避するには、次の場所から Microsoft Visual C{pp} 2010 再頒布可能パッケージ (x86) をインストールする必要があります。 http://www.microsoft.com[]

|===


== プロバイダーのホストマシンが仕様を満たしていることを確認する

SMI-S プロバイダを実行するには、プロバイダホストマシンが次の仕様を満たしている必要があります。

* プロバイダーを Hyper-V ノードに直接インストールすることはできません。代わりに、Hyper-V VM にインストールすることもできます。
* System Center Virtual Machine Manager (SCVMM) がプロバイダー ホスト マシン上で実行されていない必要があります。
* プロバイダのホストマシンは、メモリを大量に消費する他のプログラムを実行しないでください。
* プロバイダー ホスト マシンでは、他のベンダーの SMI-S プロバイダーを実行してはなりません。

