---
permalink: task-manage-storage-systems.html 
sidebar: sidebar 
keywords: smis-provider, commands, add, delete, list, storage, systems, cimom repository 
summary: NetApp SMI-S プロバイダコマンドを使用して、 CIMOM リポジトリでストレージシステムの追加、削除、一覧表示を行うことができます。また、ストレージシステムについて、 NFS および CIFS エクスポートおよびエクスポートされた LUN をリストすることもできます。 
---
= ストレージシステムを管理
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp SMI-S プロバイダコマンドを使用して、 CIMOM リポジトリでストレージシステムの追加、削除、一覧表示を行うことができます。また、ストレージシステムについて、 NFS および CIFS エクスポートおよびエクスポートされた LUN をリストすることもできます。



== 作業を開始する前に

* Administrator としてのログインクレデンシャルが必要です。
* ホストシステムに Administrator としてログインしている必要があります。




== このタスクについて

ONTAP の場合、クラスタの IP アドレスではなく SVM の管理 IP アドレスを指定する必要があり、 vsadmin ユーザのクレデンシャルを指定する必要があります。SMI-S プロバイダは、クラスタ IP アドレスまたはノード管理 IP アドレスをサポートしません。また、ノード管理またはノード SVM もサポートしません。

[NOTE]
====
SMI-S プロバイダに管理 LIF を追加するときは、管理 LIF のデータプロトコルの値を「 none 」に設定する必要があります。

====


== 手順

. NetApp SMI-S Provider にアクセスします。
. 次のいずれかの操作を実行します。
+
[cols="3*"]
|===
| アクション | コマンドを実行します | 追加情報 


 a| 
プロバイダとストレージシステムの間に HTTP 接続されたストレージシステムを追加します
 a| 
`*SMIS add_storage_sys storage_sys_user_*`
 a| 
コマンドは、プロバイダがキャッシュを更新して応答するまで最大 15 分待機します。



 a| 
プロバイダとストレージシステムの間に HTTPS 接続されたストレージシステムを追加する
 a| 
`*SMIS addsecure_storage_sys storage_sys_user_*`
 a| 
コマンドは、プロバイダがキャッシュを更新して応答するまで最大 15 分待機します。



 a| 
ストレージシステムの NFS および CIFS エクスポートを一覧表示します
 a| 
'*SMIS exports *
 a| 
なし



 a| 
CIMOM リポジトリのストレージシステムを一覧表示します
 a| 
*SMIS リスト *`
 a| 
このコマンドを実行すると、ストレージシステムを追加または削除する前に、 CIMOM リポジトリ内のストレージシステムを検証できます。



 a| 
ストレージシステムのエクスポート済み LUN をリストします
 a| 
`*SMIS LUN*`
 a| 
なし



 a| 
CIMOM リポジトリからストレージシステムを削除します
 a| 
`*SMIS DELETE_storage_sys_*`
 a| 
ストレージシステムの管理が不要になった場合は、 CIMOM リポジトリからストレージシステムを削除できます。

SMI-S プロバイダは CIMOM リポジトリ内のすべてのストレージシステムから情報を収集するため、最適なパフォーマンスを維持するには、未使用のストレージシステムをリポジトリから削除する必要があります。



 a| 
現在の CIM サーバ設定情報をリストします
 a| 
*SMIS config show *`
 a| 
なし



 a| 
ストレージシステムの FC および iSCSI ポート情報をリストします
 a| 
*SMIS イニシエータ *`
 a| 
なし



 a| 
ストレージシステムのストレージプールを一覧表示します
 a| 
'*SMIS プール *
 a| 
なし



 a| 
ストレージ・システムのトラディショナル・ボリュームとフレキシブル・ボリュームを一覧表示します
 a| 
`*SMIS VOLUMES *`
 a| 
なし

|===

