---
permalink: task-specify-the-number-of-trace-files-saved.html 
sidebar: sidebar 
keywords: trace, enable, seven trace file, pegasus trace file num, system, space 
summary: トレースが有効になっている場合、デフォルトで 7 つのトレースファイルが保存されます。さらにトレースファイルを保存する必要がある場合は、環境変数 PEGASUS_TRACE_FILE_NUM を設定して、保存するトレースファイルの最大数を増やすことができます。保存されるトレースファイルの最大数を増やす場合は、トレースファイルを保存するための十分なスペースがハードドライブに確保されていることを確認する必要があります。 
---
= 保存するトレースファイルの数を指定します
:icons: font
:imagesdir: ./media/


[role="lead"]
トレースが有効になっている場合、デフォルトで 7 つのトレースファイルが保存されます。さらにトレースファイルを保存する必要がある場合は ' 環境変数 PEGASUS_TRACE_FILE_NUM を設定して ' 保存するトレースファイルの最大数を増やすことができます保存されるトレースファイルの最大数を増やす場合は、トレースファイルを保存するための十分なスペースがハードドライブに確保されていることを確認する必要があります。



== 作業を開始する前に

* Administrator としてのログインクレデンシャルが必要です。
* ホストシステムに Administrator としてログインしている必要があります。




== このタスクについて

トレースが有効になっている場合 ' トレース情報は 'cimserver.trc' ファイルに書き込まれますトレースファイルはローテーションされます。「 cimserver.trc 」が最大トレース・ファイル・サイズに達すると、その内容は「 cimserver.trc._n_` ファイル」に移動します。デフォルトでは 'n' は 0 ～ 5 の値ですさらにトレース・ファイルを保存する必要がある場合は '_n_' の値を増やします



== 手順

. NetApp SMI-S Provider にアクセスします。
. 保存された新しいトレースファイル数を指定して '`PEGASUS_TRACE_FILE_NUM] という名前のシステムまたはユーザー環境変数を作成します
+
環境変数の作成の詳細については '_windows documentation _ を参照してください

. CIM サーバを再起動します。
+
`*SMIS cimserver restart*`


