---
permalink: task-specify-the-maximum-number-of-threads-per-message-service-queue.html 
sidebar: sidebar 
keywords: default, smi-s provider, 80 threads, per message, service queue, machine performance 
summary: デフォルトでは、 SMI-S Provider はメッセージサービスキューごとに 80 スレッドを許可します。最大スレッド値は 1 ～ 5000 で指定できます。最大スレッド数を増やすと、 SMI-S Provider マシンのパフォーマンスに影響を与える可能性があるため、この値を増やす必要があるかどうかを慎重に検討してください。 
---
= メッセージサービスキューあたりの最大スレッド数を指定します
:icons: font
:imagesdir: ./media/


[role="lead"]
デフォルトでは、 SMI-S Provider はメッセージサービスキューごとに 80 スレッドを許可します。最大スレッド値は 1 ～ 5000 で指定できます。最大スレッド数を増やすと、 SMI-S Provider マシンのパフォーマンスに影響を与える可能性があるため、この値を増やす必要があるかどうかを慎重に検討してください。

.作業を開始する前に
* Administrator としてのログインクレデンシャルが必要です。
* ホストシステムに Administrator としてログインしている必要があります。


トレース・ファイルに「不十分なリソース」出力の行が多数表示されている場合は、スレッド数を 500 ずつ増やす必要があります。

スレッドの最大数を 20 未満に設定した場合は、「 * cimcli -n root/ONTAP Niall * 」コマンドを使用してプロバイダが応答しなくなり、トレースファイルに「 Insufficient threadpool 」メッセージが返されます。この場合は、スレッド数を 500 ずつ増やす必要があります。その後、プロバイダを再起動してください。

.手順
. NetApp SMI-S Provider にアクセスします。
. 新しい最大スレッド値を使用して 'PEGASUS_MAX_THLANS_PER_SVC_QUEUE という名前のシステムまたはユーザー環境変数を作成します
+
環境変数の作成については、 Windows のマニュアルを参照してください。

. CIM サーバを再起動します。
+
`*SMIS cimserver restart*`


